### ISSUE TITLE
Doesn't circumvent YouTube's new trick of showing ads

### ISSUE THREAD

**Issue by zypherift** [MartinBraquet/youtube-adblock#5] opened 2024-06-08 16:04 UTC
Hello!

I installed this extension today because I saw that it's maintained, and I'm grateful for that! However, I encountered a small issue. Today, YouTube appears to have made a change in the way they display ads. The ads now show up as videos, which seems to trick the ad blockers into thinking they aren't ads.

I have uBlock Origin installed with up-to-date lists, and I have this extension installed as well. 

One interesting observation is that when I move my cursor away from the video, the UI hides, but the progress bar remains yellow, indicating it's an ad.

I've attached three images below to illustrate the issue:
1. ![image](https://github.com/MartinBraquet/youtube-adblock/assets/59338514/f41b0736-229f-4364-b58f-65c11ea73d73)
2. ![image](https://github.com/MartinBraquet/youtube-adblock/assets/59338514/5a07a960-c632-4c37-a6f4-f12cc784678d)
3. ![image](https://github.com/MartinBraquet/youtube-adblock/assets/59338514/b2c21bad-314b-466c-9cce-80f070a2f25c)

Thank you for your attention to this matter!

**Comment by zypherift** [comment] 2024-06-08 16:08
One more interesting thing is that in Firefox's Picture-in-Picture (PiP) player, it seems to add the ads before the video, making it one whole video with the ads in front, thus increasing its length.

**Comment by MartinBraquet** [comment] 2024-06-08 21:23
Thanks for raising this issue!
The extension detects that the video is an ad if it is in the `ad-showing` class, as done here.
https://github.com/MartinBraquet/youtube-adblock/blob/c2761701c4de2b1885bf8f7d7c20a40f923db73b/content.js#L16
I can't reproduce yet so I'll need a little help. Could you pause the ad and send here the html content of the ad section (or the whole page) so that we can see in which html class it is? To get the html content, you can right-click on the youtube page (not on the video itself as we want the firefox right click, not the youtube one), then inspect, then in the html section hover over the  sections and expand to find the section related to the video. For example, I get this right now:
```
<div class="html5-video-player ytp-transparent ytp-exp-bottom-control-flexbox ytp-modern-caption ytp-exp-ppp-update ytp-fit-cover-video ytp-bigboards ytp-hide-info-bar ytp-autonav-endscreen-cancelled-state ytp-heat-map-v2 ytp-heat-map ytp-large-width-mode ytp-fine-scrubbing-exp ad-created ad-showing ad-interrupting paused-mode" tabindex="-1" id="movie_player" data-version="/s/player/dee49cfa/player_ias.vflset/en_US/base.js" aria-label="YouTube Video Player">...
```
A search for `video-player` might help locate it as well.

Once we know in which class it is, we'll be able to adjust the code to discriminate between ad and non-ad.

**Comment by zypherift** [comment] 2024-06-09 13:36
Thanks for your response!
I've followed your steps, and created two HTML files containing two seperate examples of this ad. You can find them below. (I had to rename them to .txt, because GitHub doesn't allow uploading .html files)
[youtube.txt](https://github.com/user-attachments/files/15752672/youtube.txt)
[youtube2.txt](https://github.com/user-attachments/files/15752673/youtube2.txt)

I hope they help identify and resolve the problem.

**Comment by MartinBraquet** [comment] 2024-06-09 19:43
Thanks, the issue is that youtube does not show an `ad-showing` tag in the ad class. There is another ad tag, `ad-created`, but we can't infer based on it because this tag is also present when the ad finished and the non-ad video is running.
I am trying to find an element to discriminate between ads and non-ads for the config that youtube set at your location; could you also add another html file (same format as before) corresponding to a video just after an ad (that is, let the ad finish, then watch a few secs of the video you wanted to watch, then pause and save the html)?

**Comment by zypherift** [comment] 2024-06-10 15:02
Sure, I attached the file below.
[videoafterad.txt](https://github.com/user-attachments/files/15775279/videoafterad.txt)

One more thing that I noticed, is that there is a yellow bar instead of the red one while the ad is playing and the player is unfocused. Maybe that can help?

**Comment by MartinBraquet** [comment] 2024-06-11 06:22
Thanks, I think there is an issue with that file as there is no video in it (no `video-stream html5-main-video` class present). But I like your idea of discriminating between ads and non-ads based on the yellow bar, so I just pushed a fix to do so in the version [1.60](https://github.com/MartinBraquet/youtube-adblock/commit/c2a0ecbac517e68caab546e8ec0afcef45a349c9). It does not discriminate based on the color of the bar but rather based on whether the bar is present (it is coded by youtube as another bar that they hide when the ad is done).
Let me know if that resolves your issue (after you update the extension in your browser); if not, please re-upload the html of the video after the ad and I'll think of another way.

**Comment by MartinBraquet** [comment] 2024-06-17 18:57
@zypherift Did it the current version solve the issue?

**Comment by zypherift** [comment] 2024-06-18 13:59
Yes, it works perfectly now, sorry for the late response!

**Closed** 2024-06-18 14:36 UTC
