### ISSUE TITLE
youtube-adblock accelerating videos as well as adverts

### ISSUE THREAD

**Issue by Paladin-z** [MartinBraquet/youtube-adblock#16] opened 2024-10-25 11:05 UTC
As of today using Firefox 131.0.3 (64-bit) the addon now accelerates all youtube videos (or blanks them if hide ad is enabled), not just the adverts.

**Comment by MartinBraquet** [comment] 2024-10-25 12:12
Thanks for the feedback. There are some reviews mentioning it as well.
However, I can't reproduce locally as of now. It would help if someone can upload here the html content of a webpage where the extension fails.

**Comment by MartinBraquet** [comment] 2024-10-25 14:36
Thanks for the quick turn out. Unfortunately, I can't use that file to debug because it does not contain the video source; it was likely saved after the ad got skipped. 
Would you be able to save the html content before or while the ad is running? To do so, you can disable `hide ad` and set a low playback rate (like 3).

**Comment by Paladin-z** [comment] 2024-10-25 15:14
[youtubehtml.txt](https://github.com/user-attachments/files/17524014/youtubehtml.txt)
Hopefully this will help, the best I can do is the source while the video is being treated as an advert. After watching a dozen videos over 30minutes I can't get a single advert to show at all (which in itself is a nice problem to have).

**Comment by MartinBraquet** [comment] 2024-10-25 17:18
Thanks again. I have the same issue. The file contains only the skeleton; it does not show any video content, which needs to be loaded by the scripts.
That being said, I could reproduce some issue with video skipping that I just resolved in version 1.71. Let me know after updating your extension if it resolves your issue as well.

**Comment by Paladin-z** [comment] 2024-10-25 19:17
Thanks, I'll leave it for now. For some reason I am now seeing **no** adverts at all, not even ones being skipped. In 3hrs I've had no adverts on youtube, without having premium.

**Comment by MartinBraquet** [comment] 2024-10-27 14:55
/remind me to ask @Paladin-z for issue status in 2 weeks

**Comment by MartinBraquet** [comment] 2024-10-27 14:56
/remind me to deploy on Oct 10

**Comment by MartinBraquet** [comment] 2024-10-27 15:05
/remind me to ask @Paladin-z for issue status in 2 weeks

**Comment by nathaniel** [comment] 2024-10-27 22:55
I am seeing the same "video is being accelerated just like an ad" issue, even with version 1.71.
Thanks for a great add-on!

**Comment by Paladin-z** [comment] 2024-11-11 11:56
I'm still not seeing a single advert at all, without premium, so I can't say if 1.71 has had any affect, sorry.

**Comment by MartinBraquet** [comment] 2024-11-11 12:33
Well, it's quite nice for you then.
I did see one video speed-up a few days ago, but I couldn't reproduce it.
@nathaniel , if it still happens for you, would you be able to grep the add-on logs and post them here? You can do so by opening the web console and filtering by `ytad`, then right-click -> save all messages to file.

**Comment by nathaniel** [comment] 2024-12-16 23:59
I am no longer having this issue!

(I had made sure to check my version, restart browser, etc. back when I was seeing this issue, and it was fully reproducible. But haven't seen it again since about your last note @MartinBraquet, Nov 11...)

**Comment by MartinBraquet** [comment] 2024-12-17 09:35
Awesome! I'll close the issue for now then.

**Closed by MartinBraquet** 2024-12-17 09:35 UTC
