### ISSUE TITLE
Skip ads don't work

### ISSUE THREAD

**Issue by androidghosh** [MartinBraquet/youtube-adblock#18] opened 2024-12-10 03:33 UTC
![image](https://github.com/user-attachments/assets/db8a6228-f580-420c-9f37-cb77dd89b281)
This function do not work. This addon successfully speeding up the ads but it isn't automatically clicking the skip button, I have to do it manually. Please fix it.

**Comment by MartinBraquet** [comment] 2024-12-10 04:51
Isn't it a duplicate of #2 ?

**Comment by MartinBraquet** [comment] 2024-12-12 03:49
Okay thanks. Then I'll close this issue and increase the priority of fixing #2 .

**Closed by MartinBraquet** 2024-12-12 03:49 UTC
